"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path");
const root=path.resolve(__dirname,".."),read=file=>fs.readFileSync(path.join(root,file),"utf8");
const system=read("src/system.js"),supabase=read("src/supabase.js"),app=read("src/app.js"),permits=read("src/work-permits.js"),sql=read("database/permissions_release_v38.sql");
for(const key of ["visitors.register","visitors.edit","attendance.register","attendance.edit","compliance.edit","compliance.monthly_report"]) assert(system.includes(key),`Falta ruta ${key}`);
for(const adapter of ["createInspection","updateInspection","createIncident","updateIncident"]) assert(supabase.includes(adapter)&&app.includes(adapter),`Falta adaptador granular ${adapter}`);
assert(!app.includes('canPermission("records-write")'),"Inspecciones/incidencias no deben depender de records-write");
assert(permits.includes('can("reports.generate")')&&permits.includes('can("permits.export")'),"La exportación de permisos requiere ambos permisos");
assert(permits.includes('can("signatures.export")'),"Las imágenes de firma requieren signatures.export");
assert(permits.includes('button.dataset.permission="permits.export"'),"Los botones de exportación deben declarar data-permission");
assert(sql.includes("for r in select schemaname,tablename,policyname from pg_catalog.pg_policies")&&sql.includes("targets text[]"),"La limpieza RLS debe usar lista blanca");
assert(sql.includes("revoke insert,update,delete on table public.perfiles_usuario from authenticated"),"perfiles_usuario debe revocar escrituras cliente");
for(const type of ["inspection","inspeccion","extinguisher","extintores","firstaid","first_aid","botiquin","botiquín","tablesaw","table_saw","grinder","extensioncord","extension_cord"]) assert(sql.includes(`'${type}'`),`gravi_record_permission debe reconocer ${type}`);
for(const type of ["incident","incidente","accident","accidente"]) assert(sql.includes(`'${type}'`),`gravi_record_permission debe reconocer ${type}`);
for(const operation of ["inspections.view","inspections.create","inspections.edit"]) assert(sql.includes(`'${operation}'`),`Los tipos heredados requieren ${operation}`);
assert(sql.includes("attendance_date=current_date and public.has_gravi_permission('attendance.register')")&&sql.includes("gravi_attendance_update_allowed(attendance_date)")&&sql.includes("p_date=current_date"),"attendance.register sólo debe registrar el día operativo y no editar históricos");
assert(sql.includes("gravi_compliance_payload_allowed")&&sql.includes("gravi_v38_compliance_guard"),"Cumplimiento debe separar payloads por permiso");
assert(sql.includes("gravi_v38_permit_evidence_delete")&&sql.includes("created_by=auth.uid()"),"Evidencia de permisos requiere DELETE con propiedad");
assert(sql.includes("gravi_v38_permit_history_insert")&&sql.includes("'permits.authorize'"),"permits.authorize debe escribir historial sin permits.edit");
for(const permission of ["permits.review","permits.authorize","permits.suspend","permits.cancel","permits.close"]) assert(sql.includes(`'${permission}'`),`Las etapas auxiliares requieren ${permission}`);
assert(sql.includes("gravi_v38_signature_integrity")&&sql.includes("gravi_guard_signature_invalidation"),"Las firmas requieren trigger de integridad");
assert(sql.includes("known text[]:=array[")&&sql.includes("work_permits_storage_select"),"Storage debe limpiar nombres históricos explícitos");
const archiveGuard=sql.slice(sql.indexOf("function public.gravi_guard_archive_update"),sql.indexOf("do $$ declare r record"));
for(const [edit,archive] of [["developments.edit","developments.archive"],["works.edit","works.archive"],["contractors.edit","contractors.archive"],["workers.edit","workers.archive"]]) assert(sql.includes(`'${edit}','${archive}'`),`Falta contrato ${edit}/${archive}`);
assert(archiveGuard.indexOf("archive_changed")<archiveGuard.indexOf("has_gravi_permission(edit_key)"),"El trigger debe detectar archivado antes de aceptar edit");
assert(archiveGuard.includes("if not archive_changed")&&archiveGuard.includes("has_gravi_permission(archive_key)"),"edit y archive deben ser mutuamente excluyentes por operación");
assert(archiveGuard.includes("old_clean is distinct from new_clean"),"archive no debe permitir modificar nombre, estado o work_id");
const signatureGuard=sql.slice(sql.indexOf("function public.gravi_guard_signature_invalidation"),sql.indexOf("function public.gravi_work_permit_stage_allowed"));
assert(signatureGuard.includes("new.signature_status::text<>'invalidated'"),"signatures.invalidate sólo permite invalidated");
assert(signatureGuard.includes("new.invalidated_at is null")&&signatureGuard.includes("btrim(new.invalidation_reason)"),"Invalidar requiere fecha y motivo");
assert(signatureGuard.includes("new.invalidated_by is distinct from auth.uid()"),"Invalidar exige actor actual");
for(const protectedField of ["signature_storage_path","document_content_hash","strokes_data","signer_name"]) assert(!signatureGuard.includes(`'${protectedField}'`),`${protectedField} no debe estar entre las columnas mutables`);
assert(sql.includes("owner_id=auth.uid()::text and public.has_gravi_permission('permits.edit')")&&sql.includes("public.is_gravi_admin() or (owner_id="),"Storage work-permits exige propiedad o Administrador");
const verify=read("database/verify_permissions_v38.sql");
assert(verify.includes("expected_policies(table_name,cmd)")&&verify.includes("24_expected_policies_present"),"El verificador necesita matriz de políticas esperadas");
assert(verify.includes("expression ilike '%work-permits/%' and expression like '%!~~%' then 'evidence'"),"NOT LIKE debe clasificarse como evidencia general");
assert(verify.includes("work_permits_validate_update")&&verify.includes("validate_work_permit_update")&&verify.includes("public.has_work_permit_permission"),"Debe verificarse el trigger crítico de permisos");
assert(!sql.includes("jsonb_object_length"),"V38.2 no puede depender de jsonb_object_length");
assert(sql.includes("jsonb_typeof(coalesce(p_new,'{}'::jsonb))='object'")&&sql.includes("coalesce(p_new,'{}'::jsonb)<>'{}'::jsonb"),"Cumplimiento exige objeto JSON no vacío");
assert(sql.includes("revoke insert,update,delete on table public.registro_diario from authenticated")&&sql.includes("grant select on table public.registro_diario to authenticated"),"Registro diario debe ser SELECT directo y DML por RPC");
assert(!sql.includes("create policy gravi_v38_daily_insert")&&!sql.includes("create policy gravi_v38_daily_update"),"Registro diario no debe conservar políticas de DML cliente");
for(const rpc of ["save_daily_report_draft","close_daily_report_manual","close_due_daily_reports"]) assert(verify.includes(rpc),`Debe verificarse la RPC ${rpc}`);
assert(!sql.includes("create policy gravi_v38_signature_storage_update"),"Los archivos de firma no admiten UPDATE");
assert(sql.includes("gravi_v38_signature_storage_delete on storage.objects for delete")&&sql.includes("bucket_id='document-signatures' and public.is_gravi_admin()"),"DELETE de firma debe ser sólo administrativo");
assert(sql.includes("gravi_v38_evidence_update")&&sql.includes("owner_id=auth.uid()::text and public.has_gravi_permission('evidence.upload')"),"UPDATE de evidencia general exige propiedad");
const permitGuard=sql.slice(sql.indexOf("function public.validate_work_permit_update"),sql.indexOf("do $$begin if to_regclass('public.work_permits')"));
assert(permitGuard.includes("security definer set search_path=pg_catalog,public")&&verify.includes("'validate_work_permit_update'"),"validate_work_permit_update requiere definición completa y search_path endurecido");
assert(permitGuard.includes("new.status is not distinct from old.status")&&permitGuard.includes("has_work_permit_permission('permits.edit')"),"Sin transición sólo permits.edit permite editar");
assert(permitGuard.includes("to_jsonb(old)-allowed_fields")&&permitGuard.includes("to_jsonb(new)-allowed_fields"),"Las transiciones deben comparar OLD y NEW");
for(const field of ["status","updated_at","revision","authorized_at","authorized_by","authorized_by_supervisor","authorized_snapshot"]) assert(permitGuard.includes(`'${field}'`),`Falta clasificar el campo de transición ${field}`);
for(const field of ["description","hazards","activity_controls","participants","starts_at","ends_at","contractor_name","worker_count"]) assert(!permitGuard.match(new RegExp(`allowed_fields[^;]*'${field}'`)),`${field} no puede habilitarse durante una transición`);
assert(permitGuard.includes("old.authorized_snapshot is not null")&&permitGuard.includes("new.status<>'authorized'"),"authorized_snapshot debe permanecer inmutable y sólo nacer al autorizar");
const {hasPermission}=require("../api/permissions-contract");
for(const key of ["permits.authorize","permits.suspend","permits.close","permits.review","permits.cancel"]){const profile={active:true,role:"Supervisor SST",permissions_mode:"custom",custom_permissions:{[key]:false}};assert.strictEqual(hasPermission(profile,key),false,`custom false debe retirar ${key}`);}
assert(verify.includes("33_work_permit_transition_fields_guarded"),"Falta verificar la separación de campos de transición");
assert(sql.includes("grant select on table public.perfiles_usuario to authenticated"),"El perfil propio requiere SELECT explícito");
assert(verify.includes("signatures=3")&&verify.includes("31_signature_storage_immutable")&&verify.includes("32_evidence_update_owner"),"El verificador debe reflejar Storage V38.2");
const storage22=verify.slice(verify.indexOf("'22_storage_no_anon'"),verify.indexOf("'23_storage_scopes_separated'"));
assert(!storage22.includes("information_schema.role_table_grants"),"Storage no debe fallar por grants base de anon");
assert(storage22.includes("c.relrowsecurity")&&storage22.includes("'anon'=any(roles)")&&storage22.includes("'public'=any(roles)"),"Storage debe exigir RLS y ausencia de políticas anon/public");
assert(storage22.includes("storage.buckets")&&storage22.includes("public=false")&&storage22.includes("policyname not like 'gravi_v38_%'"),"Storage debe exigir buckets privados y familias V38");
const daily30=verify.slice(verify.indexOf("'30_daily_report_rpc_guards'"),verify.indexOf("'31_signature_storage_immutable'"));
assert(daily30.includes("save_daily_report_draft")&&daily30.includes("close_daily_report_manual")&&daily30.includes("close_due_daily_reports"),"Debe distinguir RPC manuales y cierre automático");
assert(!daily30.includes("confirm_daily_report_automatic"),"El verificador no debe exigir una RPC inexistente");
assert(daily30.includes("p.proname='can_access_daily_report'")&&daily30.includes("auth.uid()"),"save delega la identidad en can_access_daily_report");
assert(daily30.includes("has_function_privilege('anon'")&&daily30.includes("has_function_privilege('authenticated'")&&daily30.includes("has_function_privilege('service_role'"),"El cierre automático debe ser exclusivo de service_role");
console.log("Rutas granulares V38 verificadas.");
