-- Solo lectura. Ejecutar después de permissions_release_v38.sql.
with
mandatory(table_name) as(values('desarrollos'),('obras'),('contratistas'),('trabajadores'),('visitantes'),('asistencia'),('registros'),('investigaciones'),('historial'),('cumplimiento_estado'),('estado_aplicacion'),('perfiles_usuario')),
optional(table_name) as(values('registro_diario'),('work_user_assignments'),('daily_report_versions'),('daily_report_closure_log'),('work_permits'),('work_permit_approvals'),('work_permit_evidence'),('work_permit_history'),('document_signatures'),('document_signature_events'),('format_categories'),('dynamic_formats'),('format_fields'),('format_records'),('format_versions'),('format_field_templates')),
targets as(select table_name from mandatory union all select table_name from optional),
expected_policies(table_name,cmd) as(values
 ('desarrollos','SELECT'),('desarrollos','INSERT'),('desarrollos','UPDATE'),('desarrollos','DELETE'),('obras','SELECT'),('obras','INSERT'),('obras','UPDATE'),('obras','DELETE'),
 ('contratistas','SELECT'),('contratistas','INSERT'),('contratistas','UPDATE'),('contratistas','DELETE'),('trabajadores','SELECT'),('trabajadores','INSERT'),('trabajadores','UPDATE'),('trabajadores','DELETE'),
 ('visitantes','SELECT'),('visitantes','INSERT'),('visitantes','UPDATE'),('visitantes','DELETE'),('asistencia','SELECT'),('asistencia','INSERT'),('asistencia','UPDATE'),('asistencia','DELETE'),
 ('registros','SELECT'),('registros','INSERT'),('registros','UPDATE'),('registros','DELETE'),('investigaciones','SELECT'),('investigaciones','INSERT'),('investigaciones','UPDATE'),('investigaciones','DELETE'),
 ('historial','SELECT'),('historial','INSERT'),('historial','UPDATE'),('historial','DELETE'),('cumplimiento_estado','SELECT'),('cumplimiento_estado','INSERT'),('cumplimiento_estado','UPDATE'),('cumplimiento_estado','DELETE'),
 ('estado_aplicacion','SELECT'),('estado_aplicacion','ALL'),('perfiles_usuario','SELECT'),
 ('registro_diario','SELECT'),('work_user_assignments','SELECT'),('work_user_assignments','INSERT'),('work_user_assignments','UPDATE'),('work_user_assignments','DELETE'),
 ('daily_report_versions','SELECT'),('daily_report_closure_log','SELECT'),('work_permits','SELECT'),('work_permits','INSERT'),('work_permits','UPDATE'),('work_permits','DELETE'),
 ('work_permit_approvals','SELECT'),('work_permit_approvals','INSERT'),('work_permit_evidence','SELECT'),('work_permit_evidence','INSERT'),('work_permit_evidence','DELETE'),('work_permit_history','SELECT'),('work_permit_history','INSERT'),
 ('document_signatures','SELECT'),('document_signatures','INSERT'),('document_signatures','UPDATE'),('document_signatures','DELETE'),('document_signature_events','SELECT'),('document_signature_events','INSERT'),
 ('format_categories','SELECT'),('format_categories','INSERT'),('format_categories','UPDATE'),('format_categories','DELETE'),('dynamic_formats','SELECT'),('dynamic_formats','INSERT'),('dynamic_formats','UPDATE'),('dynamic_formats','DELETE'),
 ('format_fields','SELECT'),('format_fields','INSERT'),('format_fields','UPDATE'),('format_fields','DELETE'),('format_records','SELECT'),('format_records','INSERT'),('format_records','UPDATE'),('format_records','DELETE'),
 ('format_versions','SELECT'),('format_versions','INSERT'),('format_versions','UPDATE'),('format_versions','DELETE'),('format_field_templates','SELECT'),('format_field_templates','INSERT'),('format_field_templates','UPDATE'),('format_field_templates','DELETE')),
policies as(select p.* from pg_catalog.pg_policies p join targets t on t.table_name=p.tablename where p.schemaname='public'),
checks(test,result,detail) as(
 select '01_mandatory_tables_exist',case when count(*) filter(where c.oid is null)>0 then 'FAIL' else 'PASS' end,string_agg(m.table_name,', ') filter(where c.oid is null) from mandatory m left join pg_catalog.pg_class c on c.oid=to_regclass('public.'||m.table_name)
 union all select '02_optional_tables',case when c.oid is null then 'SKIP' else 'PASS' end,o.table_name from optional o left join pg_catalog.pg_class c on c.oid=to_regclass('public.'||o.table_name)
 union all select '03_single_effective_insert_policy',case when exists(select 1 from policies where permissive='PERMISSIVE' and cmd in('INSERT','ALL') group by tablename having count(*)>1) then 'FAIL' else 'PASS' end,'ALL cuenta como INSERT'
 union all select '04_single_effective_update_policy',case when exists(select 1 from policies where permissive='PERMISSIVE' and cmd in('UPDATE','ALL') group by tablename having count(*)>1) then 'FAIL' else 'PASS' end,'ALL cuenta como UPDATE'
 union all select '05_single_effective_delete_policy',case when exists(select 1 from policies where permissive='PERMISSIVE' and cmd in('DELETE','ALL') group by tablename having count(*)>1) then 'FAIL' else 'PASS' end,'ALL cuenta como DELETE'
 union all select '06_no_legacy_policy_logic',case when exists(select 1 from policies where (coalesce(qual,'')||coalesce(with_check,'')) ilike '%can_gravi_operate%' or policyname in('gravi_read','gravi_insert','gravi_update','profiles_update')) then 'FAIL' else 'PASS' end,'can_gravi_operate y nombres legados'
 union all select '07_profiles_select_only',case when exists(select 1 from information_schema.role_table_grants where table_schema='public' and table_name='perfiles_usuario' and grantee='authenticated' and privilege_type in('INSERT','UPDATE','DELETE')) then 'FAIL' when not exists(select 1 from information_schema.role_table_grants where table_schema='public' and table_name='perfiles_usuario' and grantee='authenticated' and privilege_type='SELECT') then 'FAIL' else 'PASS' end,'SELECT concedido; INSERT/UPDATE/DELETE revocados'
 union all select '08_no_anon_operational_grants',case when exists(select 1 from information_schema.role_table_grants g join targets t on t.table_name=g.table_name where g.table_schema='public' and g.grantee='anon') then 'FAIL' else 'PASS' end,'tablas objetivo'
 union all select '09_hardened_function_search_path',case when exists(select 1 from pg_catalog.pg_proc p join pg_catalog.pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('has_gravi_permission','role_has_default_permission','is_gravi_admin','gravi_record_permission','gravi_attendance_update_allowed','gravi_compliance_payload_allowed','gravi_guard_compliance_update','gravi_guard_signature_invalidation','gravi_work_permit_stage_allowed','gravi_guard_archive_update','can_access_daily_report','has_work_permit_permission','validate_work_permit_update') and not exists(select 1 from unnest(coalesce(p.proconfig,array[]::text[])) c where c in('search_path=pg_catalog, public','search_path='))) then 'FAIL' else 'PASS' end,'pg_proc.proconfig'
 union all select '10_permits_signatures_non_delete_central',case when exists(select 1 from policies where tablename in('work_permits','work_permit_approvals','work_permit_evidence','work_permit_history','document_signatures','document_signature_events') and cmd not in('DELETE') and (coalesce(qual,'')||coalesce(with_check,'')) not ilike '%has_gravi_permission%' and (coalesce(qual,'')||coalesce(with_check,'')) not ilike '%gravi_work_permit_stage_allowed%') then 'FAIL' else 'PASS' end,'SELECT/INSERT/UPDATE'
 union all select '11_permits_signatures_delete_authorized',case when exists(select 1 from policies where tablename in('work_permits','work_permit_evidence','document_signatures') and cmd='DELETE' and (coalesce(qual,'')||coalesce(with_check,'')) not ilike '%is_gravi_admin%' and (coalesce(qual,'')||coalesce(with_check,'')) not ilike '%has_gravi_permission%') then 'FAIL' else 'PASS' end,'DELETE administrativo o específico'
 union all select '12_existing_targets_rls_enabled',case when exists(select 1 from targets t join pg_catalog.pg_class c on c.oid=to_regclass('public.'||t.table_name) where not c.relrowsecurity) then 'FAIL' else 'PASS' end,'tablas existentes'
 union all select '13_legacy_record_types',case when position('extinguisher' in d)>0 and position('firstaid' in d)>0 and position('first_aid' in d)>0 and position('botiquín' in d)>0 and position('tablesaw' in d)>0 and position('table_saw' in d)>0 and position('grinder' in d)>0 and position('extensioncord' in d)>0 and position('extension_cord' in d)>0 and position('inspections.view' in d)>0 and position('inspections.create' in d)>0 and position('inspections.edit' in d)>0 then 'PASS' else 'FAIL' end,'lectura/inserción/edición' from (select pg_catalog.pg_get_functiondef('public.gravi_record_permission(jsonb,text,text)'::regprocedure) d)x
 union all select '14_work_permit_evidence_delete',case when to_regclass('public.work_permit_evidence') is null then 'SKIP' when exists(select 1 from policies where tablename='work_permit_evidence' and cmd='DELETE' and qual ilike '%permits.edit%' and qual ilike '%created_by%') then 'PASS' else 'FAIL' end,'propiedad o Administrador'
 union all select '15_transition_history_permissions',case when to_regclass('public.work_permit_history') is null then 'SKIP' when exists(select 1 from policies where tablename='work_permit_history' and cmd='INSERT' and with_check ilike '%permits.authorize%' and with_check ilike '%permits.cancel%' and with_check ilike '%permits.close%') then 'PASS' else 'FAIL' end,'authorize sin permits.edit también escribe historial'
 union all select '16_attendance_register_not_historical_edit',case when pg_catalog.pg_get_functiondef('public.gravi_attendance_update_allowed(date)'::regprocedure) ilike '%p_date=current_date%' and pg_catalog.pg_get_functiondef('public.gravi_attendance_update_allowed(date)'::regprocedure) ilike '%attendance.edit%' then 'PASS' else 'FAIL' end,'fecha actual vs histórica'
 union all select '17_compliance_permissions_separated',case when pg_catalog.pg_get_functiondef('public.gravi_compliance_payload_allowed(jsonb,jsonb)'::regprocedure) ilike '%complianceMatrix%' and pg_catalog.pg_get_functiondef('public.gravi_compliance_payload_allowed(jsonb,jsonb)'::regprocedure) ilike '%histories%' and exists(select 1 from pg_catalog.pg_trigger where tgrelid=to_regclass('public.cumplimiento_estado') and tgname='gravi_v38_compliance_guard' and not tgisinternal) then 'PASS' else 'FAIL' end,'edit/nom_matrix/monthly_report'
 union all select '18_signature_integrity_trigger',case when to_regclass('public.document_signatures') is null then 'SKIP' when exists(select 1 from pg_catalog.pg_trigger where tgrelid=to_regclass('public.document_signatures') and tgname='gravi_v38_signature_integrity' and not tgisinternal) then 'PASS' else 'FAIL' end,'contenido firmado inmutable'
 union all select '19_storage_no_old_policies',case when exists(select 1 from pg_catalog.pg_policies where schemaname='storage' and tablename='objects' and policyname in('evidencias_select_authenticated','evidencias_insert_operational','evidencias_update_operational','evidencias_delete_admin','work_permits_storage_select','work_permits_storage_insert','work_permits_storage_update','work_permits_storage_delete','document_signatures_storage_select','document_signatures_storage_insert','document_signatures_storage_update','document_signatures_storage_delete')) then 'FAIL' else 'PASS' end,'lista explícita'
 union all select '20_storage_no_legacy_authority',case when exists(select 1 from pg_catalog.pg_policies where schemaname='storage' and tablename='objects' and (coalesce(qual,'')||coalesce(with_check,'')) ~* '(can_gravi_operate|has_work_permit_permission)') then 'FAIL' else 'PASS' end,'Storage GRAVI'
 union all select '21_storage_unique_scope_operation',case when exists(select 1 from (select expected.scope,expected.cmd,count(scoped.policyname) n from (values('evidence','SELECT'),('evidence','INSERT'),('evidence','UPDATE'),('evidence','DELETE'),('work-permits','SELECT'),('work-permits','INSERT'),('work-permits','UPDATE'),('work-permits','DELETE'),('signatures','SELECT'),('signatures','INSERT'),('signatures','DELETE'))expected(scope,cmd) left join (select policyname,cmd,case when policyname like 'gravi_v38_evidence_%' then 'evidence' when policyname like 'gravi_v38_permit_storage_%' then 'work-permits' when policyname like 'gravi_v38_signature_storage_%' then 'signatures' when expression ilike '%document-signatures%' then 'signatures' when expression ilike '%work-permits/%' and expression like '%!~~%' then 'evidence' when expression ilike '%work-permits/%' then 'work-permits' when expression ilike '%evidencias%' then 'evidence' end scope from (select policyname,cmd,coalesce(qual,'')||coalesce(with_check,'') expression from pg_catalog.pg_policies where schemaname='storage' and tablename='objects' and permissive='PERMISSIVE')p)scoped on scoped.scope=expected.scope and scoped.cmd=expected.cmd group by expected.scope,expected.cmd having count(scoped.policyname)<>1)x) or exists(select 1 from pg_catalog.pg_policies where schemaname='storage' and tablename='objects' and permissive='PERMISSIVE' and policyname like 'gravi_v38_signature_storage_%' and cmd='UPDATE') then 'FAIL' else 'PASS' end,'evidencia/permisos completos; firmas SELECT, INSERT y DELETE'
 union all select '22_storage_no_anon',case
  when not exists(select 1 from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='storage' and c.relname='objects' and c.relrowsecurity) then 'FAIL'
  when exists(select 1 from pg_catalog.pg_policies where schemaname='storage' and tablename='objects' and ('anon'=any(roles) or 'public'=any(roles))) then 'FAIL'
  when (select count(*) from storage.buckets where id in('evidencias','document-signatures') and public=false)<>2 then 'FAIL'
  when exists(select 1 from pg_catalog.pg_policies where schemaname='storage' and tablename='objects' and permissive='PERMISSIVE' and policyname not like 'gravi_v38_%') then 'FAIL'
  else 'PASS' end,'RLS activo; buckets privados; sin políticas para anon/public'
 union all select '23_storage_scopes_separated',case when (select count(*) from pg_catalog.pg_policies where schemaname='storage' and tablename='objects' and policyname like 'gravi_v38_evidence_%')=4 and (select count(*) from pg_catalog.pg_policies where schemaname='storage' and tablename='objects' and policyname like 'gravi_v38_permit_storage_%')=4 and (select count(*) from pg_catalog.pg_policies where schemaname='storage' and tablename='objects' and policyname like 'gravi_v38_signature_storage_%')=3 then 'PASS' else 'FAIL' end,'evidence=4/work-permits=4/signatures=3'
 union all select '24_expected_policies_present',case when exists(select 1 from expected_policies e where to_regclass('public.'||e.table_name) is not null and not exists(select 1 from policies p where p.tablename=e.table_name and p.cmd=e.cmd and 'authenticated'=any(p.roles))) then 'FAIL' else 'PASS' end,'matriz obligatoria y tablas opcionales existentes'
 union all select '25_no_unexpected_authenticated_writes',case when exists(select 1 from policies p where p.cmd in('INSERT','UPDATE','DELETE','ALL') and 'authenticated'=any(p.roles) and not exists(select 1 from expected_policies e where e.table_name=p.tablename and e.cmd=p.cmd)) then 'FAIL' else 'PASS' end,'operaciones fuera de expected_policies'
 union all select '26_archive_guards_present',case when exists(select 1 from (values('desarrollos'),('obras'),('contratistas'),('trabajadores'))t(table_name) where to_regclass('public.'||t.table_name) is not null and not exists(select 1 from pg_catalog.pg_trigger g where g.tgrelid=to_regclass('public.'||t.table_name) and g.tgname='gravi_v38_archive_guard' and not g.tgisinternal)) then 'FAIL' else 'PASS' end,'desarrollos/obras/contratistas/trabajadores'
 union all select '27_work_permit_validation_trigger',case when to_regclass('public.work_permits') is null then 'SKIP' when not exists(select 1 from pg_catalog.pg_trigger where tgrelid=to_regclass('public.work_permits') and tgname='work_permits_validate_update' and not tgisinternal) then 'FAIL' when not exists(select 1 from pg_catalog.pg_proc p join pg_catalog.pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='validate_work_permit_update' and pg_catalog.pg_get_functiondef(p.oid) ilike '%public.has_work_permit_permission%') then 'FAIL' when not exists(select 1 from pg_catalog.pg_proc p join pg_catalog.pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='has_work_permit_permission' and pg_catalog.pg_get_functiondef(p.oid) ilike '%public.has_gravi_permission%') then 'FAIL' else 'PASS' end,'trigger, función, wrapper y autoridad central'
 union all select '28_no_jsonb_object_length',case when exists(select 1 from pg_catalog.pg_proc p join pg_catalog.pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='gravi_compliance_payload_allowed' and pg_catalog.pg_get_functiondef(p.oid) ilike '%jsonb_object_length%') then 'FAIL' else 'PASS' end,'función inexistente ausente'
 union all select '29_daily_report_select_only_grant',case when to_regclass('public.registro_diario') is null then 'SKIP' when exists(select 1 from information_schema.role_table_grants where table_schema='public' and table_name='registro_diario' and grantee='authenticated' and privilege_type in('INSERT','UPDATE','DELETE')) then 'FAIL' when not exists(select 1 from information_schema.role_table_grants where table_schema='public' and table_name='registro_diario' and grantee='authenticated' and privilege_type='SELECT') then 'FAIL' else 'PASS' end,'authenticated sólo SELECT'
 union all select '30_daily_report_rpc_guards',case
  when to_regclass('public.registro_diario') is null then 'SKIP'
  when exists(select 1 from (values('save_daily_report_draft'),('close_daily_report_manual'))r(proname) where not exists(select 1 from pg_catalog.pg_proc p join pg_catalog.pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname=r.proname and p.prosecdef and pg_catalog.pg_get_functiondef(p.oid) ilike '%public.can_access_daily_report%')) then 'FAIL'
  when not exists(select 1 from pg_catalog.pg_proc p join pg_catalog.pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='can_access_daily_report' and p.prosecdef and pg_catalog.pg_get_functiondef(p.oid) ilike '%auth.uid()%' and exists(select 1 from unnest(coalesce(p.proconfig,array[]::text[]))c where c in('search_path=pg_catalog, public','search_path='))) then 'FAIL'
  when not exists(select 1 from pg_catalog.pg_proc p join pg_catalog.pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='close_due_daily_reports' and p.prosecdef and pg_catalog.pg_get_functiondef(p.oid) ilike '%public.registro_diario%' and pg_catalog.pg_get_functiondef(p.oid) ilike '%public.daily_report_closure_log%' and not pg_catalog.has_function_privilege('anon',p.oid,'EXECUTE') and not pg_catalog.has_function_privilege('authenticated',p.oid,'EXECUTE') and pg_catalog.has_function_privilege('service_role',p.oid,'EXECUTE')) then 'FAIL'
  else 'PASS' end,'RPC manuales protegidas; cierre automático exclusivo de service_role'
 union all select '31_signature_storage_immutable',case when exists(select 1 from pg_catalog.pg_policies where schemaname='storage' and tablename='objects' and policyname like 'gravi_v38_signature_storage_%' and cmd='UPDATE') then 'FAIL' when not exists(select 1 from pg_catalog.pg_policies where schemaname='storage' and tablename='objects' and policyname='gravi_v38_signature_storage_delete' and cmd='DELETE' and qual ilike '%is_gravi_admin%' and qual not ilike '%signatures.invalidate%') then 'FAIL' else 'PASS' end,'sin UPDATE; DELETE sólo Administrador'
 union all select '32_evidence_update_owner',case when not exists(select 1 from pg_catalog.pg_policies where schemaname='storage' and tablename='objects' and policyname='gravi_v38_evidence_update' and cmd='UPDATE' and qual ilike '%owner_id%' and qual ilike '%auth.uid%' and qual ilike '%is_gravi_admin%' and with_check ilike '%owner_id%' and with_check ilike '%auth.uid%') then 'FAIL' else 'PASS' end,'propietario con evidence.upload o Administrador'
 union all select '33_work_permit_transition_fields_guarded',case when to_regclass('public.work_permits') is null then 'SKIP' when not exists(select 1 from pg_catalog.pg_proc p join pg_catalog.pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='validate_work_permit_update' and p.prosecdef and exists(select 1 from unnest(coalesce(p.proconfig,array[]::text[]))c where c='search_path=pg_catalog, public') and pg_catalog.pg_get_functiondef(p.oid) ilike '%new.status is not distinct from old.status%' and pg_catalog.pg_get_functiondef(p.oid) ilike '%to_jsonb(old)%allowed_fields%' and pg_catalog.pg_get_functiondef(p.oid) ilike '%to_jsonb(new)%allowed_fields%' and pg_catalog.pg_get_functiondef(p.oid) ilike '%public.has_work_permit_permission%' and pg_catalog.pg_get_functiondef(p.oid) ilike '%old.authorized_snapshot is not null%' and pg_catalog.pg_get_functiondef(p.oid) ilike '%authorized_by_supervisor%' and pg_catalog.pg_get_functiondef(p.oid) ilike '%campos ordinarios%') then 'FAIL' else 'PASS' end,'edición ordinaria separada de transiciones'
)
select test,result,coalesce(detail,'') detail from checks order by test,detail;
