(function createEvidenceManager(global){
  "use strict";

  const ALLOWED=Object.freeze(["image/jpeg","image/png","image/webp"]),MAX_FILES=6,MAX_BYTES=12582912,MAX_DIMENSION=1600,QUALITY=.8;
  const preparedFiles=new Map();
  const queue=()=>global.GraviOfflineEvidenceQueue;
  const uuid=()=>global.crypto?.randomUUID?.()||`evidence-${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const sanitize=value=>String(value||"").replace(/[^a-zA-Z0-9_-]/g,"_").replace(/_+/g,"_").slice(0,120)||"unknown";
  async function sniffMime(file){const bytes=new Uint8Array(await file.slice(0,12).arrayBuffer());if(bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff)return"image/jpeg";if(bytes[0]===0x89&&bytes[1]===0x50&&bytes[2]===0x4e&&bytes[3]===0x47)return"image/png";if(String.fromCharCode(...bytes.slice(0,4))==="RIFF"&&String.fromCharCode(...bytes.slice(8,12))==="WEBP")return"image/webp";return"";}
  function selectFiles(source,options={}){const files=[...(source?.files||source||[])],limit=Math.min(options.maxFiles||MAX_FILES,MAX_FILES),accepted=files.slice(0,limit),rejected=files.slice(limit).map(file=>({file,message:`${file.name}: máximo ${limit} fotografías.`}));return{accepted,rejected};}
  async function compress(file,mime){if(!global.createImageBitmap||!document.createElement)return{blob:file,width:null,height:null};const bitmap=await createImageBitmap(file,{imageOrientation:"from-image"}),scale=Math.min(1,MAX_DIMENSION/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext("2d").drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const output=mime==="image/png"?"image/png":mime;const blob=await new Promise((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error("No fue posible preparar la imagen.")),output,output==="image/png"?undefined:QUALITY));return{blob,width:canvas.width,height:canvas.height};}
  async function prepareImages(files,options={}){const selection=selectFiles(files,options),prepared=[],rejected=[...selection.rejected];for(const file of selection.accepted){try{if(file.size>MAX_BYTES)throw new Error("excede el límite de 12 MiB");const realMime=await sniffMime(file);if(!ALLOWED.includes(realMime)||file.type&&file.type!==realMime)throw new Error("formato no compatible");const compressed=await compress(file,realMime),clientUuid=uuid(),objectUrl=URL.createObjectURL(compressed.blob),item={clientUuid,blob:compressed.blob,mimeType:realMime,originalName:file.name||"evidencia",originalSize:file.size,sizeBytes:compressed.blob.size,width:compressed.width,height:compressed.height,caption:"",objectUrl,status:"local",createdAt:new Date().toISOString()};preparedFiles.set(clientUuid,item);prepared.push(item);}catch(error){rejected.push({file,message:`${file.name}: ${error.message}.`});}}return{prepared,rejected};}
  function renderPreview(container,items,options={}){if(!container)return;container.innerHTML=items.map(item=>`<article class="evidence-preview" data-evidence-preview="${item.clientUuid}"><button type="button" data-open-prepared="${item.clientUuid}" aria-label="Abrir ${escapeHtml(item.originalName)}"><img src="${item.objectUrl}" alt="Vista previa de ${escapeHtml(item.originalName)}"></button><div><strong>${escapeHtml(item.originalName)}</strong><small>${formatBytes(item.sizeBytes)} · ${escapeHtml(item.status)}</small><label>Descripción<input data-evidence-caption="${item.clientUuid}" value="${escapeHtml(item.caption||"")}"></label></div><button type="button" data-remove-prepared="${item.clientUuid}" aria-label="Eliminar ${escapeHtml(item.originalName)}">Eliminar</button></article>`).join("");container.querySelectorAll("[data-remove-prepared]").forEach(button=>button.onclick=()=>{const remaining=removePreparedFile(button.dataset.removePrepared,items);options.onChange?.(remaining);});container.querySelectorAll("[data-open-prepared]").forEach(button=>button.onclick=()=>openViewer(items,items.findIndex(item=>item.clientUuid===button.dataset.openPrepared)));container.querySelectorAll("[data-evidence-caption]").forEach(input=>input.oninput=()=>{const item=items.find(row=>row.clientUuid===input.dataset.evidenceCaption);if(item)item.caption=input.value;});}
  function removePreparedFile(clientUuid,items=[]){const item=preparedFiles.get(clientUuid)||items.find(row=>row.clientUuid===clientUuid);if(item?.objectUrl)URL.revokeObjectURL(item.objectUrl);preparedFiles.delete(clientUuid);return items.filter(row=>row.clientUuid!==clientUuid);}
  async function saveOffline(items,record={}){if(!queue())throw new Error("La cola offline de evidencias no está disponible.");const saved=[];for(const item of items){const row=await queue().save({clientUuid:item.clientUuid||uuid(),blob:item.blob,mimeType:item.mimeType||item.blob?.type||"",originalName:item.originalName||"evidencia",originalSize:item.originalSize||item.blob?.size||0,sizeBytes:item.sizeBytes||item.blob?.size||0,width:item.width??null,height:item.height??null,caption:item.caption||"",recordType:record.recordType||"general",recordId:record.recordId||"",workId:record.workId||"",evidenceStage:record.evidenceStage||"general",sourceModule:record.sourceModule||record.recordType||"general",sourceEntryId:record.sourceEntryId||record.recordId||"",metadata:{...(record.metadata||{}),original_name:item.originalName||"evidencia"},status:"pending"});saved.push(row);if(item.objectUrl)URL.revokeObjectURL(item.objectUrl);preparedFiles.delete(item.clientUuid);}return saved;}
  function storagePath(item){const ext={"image/jpeg":"jpg","image/png":"png","image/webp":"webp"}[item.mimeType]||"bin",base=item.recordType==="preventive_control"?"preventive-controls":"work-evidence";return`${base}/${sanitize(item.workId)}/${sanitize(item.recordId)}/${sanitize(item.clientUuid)}.${ext}`;}
  async function uploadPending(){if(!navigator.onLine||!global.GraviSupabase?.isAuthenticated?.()||!global.GraviSupabase?.evidence)return{synced:0,failed:0,pending:true};const items=await queue().pending();let synced=0,failed=0;for(const item of items){try{await queue().update(item.clientUuid,{status:"uploading",attempts:Number(item.attempts||0)+1,lastError:""});const path=storagePath(item);await global.GraviSupabase.evidence.uploadFile(path,item.blob,item.mimeType);await global.GraviSupabase.evidence.create({...item,storage_path:path,client_uuid:item.clientUuid,evidence_stage:item.evidenceStage,control_id:item.recordType==="preventive_control"?item.recordId:null});await queue().update(item.clientUuid,{status:"synced",storagePath:path,blob:null,syncedAt:new Date().toISOString()});synced++;}catch(error){console.error(`[GraviEvidenceManager:upload:${item.clientUuid}]`,error);await queue().update(item.clientUuid,{status:"error",lastError:error?.message||"Error de sincronización"});failed++;}}return{synced,failed,pending:false};}
  async function getSignedUrl(path,expiresIn=900){if(!path)return"";return global.GraviSupabase?.evidence?.getSignedUrl?.(path,expiresIn)||"";}
  async function listByRecord(recordType,recordId){const local=await queue().list({recordType,recordId}),remote=await global.GraviRepositories?.preventiveEvidence?.listByRecord?.(recordId)||[],seen=new Set(local.map(item=>item.clientUuid));return[...local,...remote.filter(item=>!seen.has(item.client_uuid||item.clientUuid))];}
  async function retry(clientUuid){await queue().update(clientUuid,{status:"pending",lastError:""});return uploadPending();}
  function getAvailableCount(items=[]){return (items||[]).filter(item=>item&&!item.deletedAt&&(item.blob||item.objectUrl||item.storagePath||item.storage_path||global.GraviLegacyCaptureAdapter?.hasAvailablePhoto?.(item))).length;}
  let viewerItems=[],viewerIndex=0,viewerReturnFocus=null;
  function ensureViewer(){let modal=document.querySelector("#evidenceManagerViewer");if(modal)return modal;modal=document.createElement("div");modal.id="evidenceManagerViewer";modal.className="evidence-viewer";modal.hidden=true;modal.innerHTML=`<div class="evidence-viewer-backdrop" data-viewer-close></div><section role="dialog" aria-modal="true" aria-labelledby="evidenceViewerTitle"><header><h2 id="evidenceViewerTitle">Evidencia</h2><button type="button" data-viewer-close aria-label="Cerrar visor">Cerrar</button></header><div data-viewer-media></div><dl data-viewer-meta></dl><footer><button type="button" data-viewer-prev>Anterior</button><button type="button" data-viewer-source>Abrir registro origen</button><button type="button" data-viewer-next>Siguiente</button></footer></section>`;modal.addEventListener("click",event=>{if(event.target.closest("[data-viewer-close]"))closeViewer();if(event.target.closest("[data-viewer-prev]"))renderViewer(viewerIndex-1);if(event.target.closest("[data-viewer-next]"))renderViewer(viewerIndex+1);if(event.target.closest("[data-viewer-source]"))viewerItems[viewerIndex]?.openSource?.();});modal.addEventListener("keydown",event=>{if(event.key==="Escape")closeViewer();if(event.key==="ArrowLeft")renderViewer(viewerIndex-1);if(event.key==="ArrowRight")renderViewer(viewerIndex+1);if(event.key==="Tab"){const controls=[...modal.querySelectorAll("button:not([disabled])")],first=controls[0],last=controls.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}});document.body.append(modal);return modal;}
  async function resolveSource(item){if(item.objectUrl)return item.objectUrl;if(item.blob)return URL.createObjectURL(item.blob);if(item.photo&&global.GraviLegacyCaptureAdapter?.hasAvailablePhoto?.(item))return item.photo;if(item.storagePath||item.storage_path)return getSignedUrl(item.storagePath||item.storage_path);return"";}
  async function renderViewer(index){if(!viewerItems.length)return;viewerIndex=(index+viewerItems.length)%viewerItems.length;const item=viewerItems[viewerIndex],modal=ensureViewer(),source=await resolveSource(item);modal.querySelector("[data-viewer-media]").innerHTML=source?`<img src="${source}" alt="${escapeHtml(item.caption||item.originalName||"Evidencia")}">`:'<p class="evidence-unavailable">La evidencia está referenciada, pero el archivo no está disponible.</p>';modal.querySelector("[data-viewer-meta]").innerHTML=`<dt>Descripción</dt><dd>${escapeHtml(item.caption||"Sin descripción")}</dd><dt>Fecha</dt><dd>${escapeHtml(item.createdAt||item.created_at||"—")}</dd><dt>Usuario</dt><dd>${escapeHtml(item.createdByName||item.created_by||"—")}</dd><dt>Obra</dt><dd>${escapeHtml(item.workName||item.workId||"—")}</dd><dt>Registro</dt><dd>${escapeHtml(item.recordFolio||item.recordId||"—")}</dd><dt>Sincronización</dt><dd>${escapeHtml(item.status||item.syncStatus||"—")}</dd>`;modal.querySelector("[data-viewer-prev]").disabled=viewerItems.length<2;modal.querySelector("[data-viewer-next]").disabled=viewerItems.length<2;modal.querySelector("[data-viewer-source]").hidden=!item.openSource;}
  function openViewer(items,index=0){viewerItems=Array.isArray(items)?items:[items];viewerIndex=index;viewerReturnFocus=document.activeElement;const modal=ensureViewer();modal.hidden=false;document.body.classList.add("evidence-viewer-open");renderViewer(index);modal.querySelector("[data-viewer-close]").focus();return true;}
  function closeViewer(){const modal=document.querySelector("#evidenceManagerViewer");if(modal)modal.hidden=true;document.body.classList.remove("evidence-viewer-open");viewerReturnFocus?.focus?.();viewerReturnFocus=null;}
  function formatBytes(bytes){if(bytes<1024)return`${bytes||0} B`;if(bytes<1048576)return`${(bytes/1024).toFixed(1)} KB`;return`${(bytes/1048576).toFixed(1)} MB`;}
  function escapeHtml(value){return String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));}
  global.addEventListener("online",()=>uploadPending());global.addEventListener("gvc:auth-ready",()=>uploadPending());
  global.GraviEvidenceManager=Object.freeze({selectFiles,prepareImages,renderPreview,removePreparedFile,saveOffline,uploadPending,getSignedUrl,openViewer,closeViewer,listByRecord,retry,getAvailableCount,constants:Object.freeze({ALLOWED,MAX_FILES,MAX_BYTES,MAX_DIMENSION,QUALITY})});
})(window);
