(function createIncidentStorage(global){
  "use strict";

  const DRAFT_PREFIX="gvc-reporte-seguridad-draft-v1-",RECORDS_KEY="gvc-extintores-records-v1",MIGRATION_KEY="gvc-incident-storage-migration-v50",LIGHT_LIMIT_BYTES=64*1024;
  const now=()=>new Date().toISOString();
  const uuid=()=>global.crypto?.randomUUID?.()||`v50-${Date.now()}-${Math.random().toString(16).slice(2)}`;
  function isQuotaError(error){return error?.name==="QuotaExceededError"||error?.code===22||global.DOMException&&error instanceof global.DOMException&&/quota/i.test(`${error.name} ${error.message}`);}
  function serializedBytes(value){const text=typeof value==="string"?value:JSON.stringify(value);return global.TextEncoder?new TextEncoder().encode(text).byteLength:text.length*2;}
  function dataUrl(value){return typeof value==="string"&&/^data:[^;,]+(?:;[^,]*)?;base64,/i.test(value);}
  function evidenceReference(item={}){if(typeof item==="string")return dataUrl(item)?null:{storageUrl:item};return{clientUuid:item.clientUuid||item.id||uuid(),id:item.id||item.clientUuid||"",comment:item.comment||item.caption||"",caption:item.caption||item.comment||"",syncStatus:item.syncStatus||item.status||(item.storagePath?"synced":"pending"),storagePath:item.storagePath||item.storage_path||"",storageUrl:item.storageUrl||"",mimeType:item.mimeType||item.blob?.type||"",originalName:item.originalName||"",sizeBytes:item.sizeBytes||item.blob?.size||item.compressedSize||0,createdAt:item.createdAt||now()};}
  function compact(value,key=""){
    if(value==null||typeof value==="number"||typeof value==="boolean")return value;
    if(value instanceof Blob||global.File&&value instanceof global.File)return undefined;
    if(typeof value==="string")return dataUrl(value)||key==="objectUrl"||key==="src"&&/^blob:/i.test(value)?undefined:value;
    if(Array.isArray(value))return value.map((item,index)=>key==="evidence"?evidenceReference(item):compact(item,String(index))).filter(item=>item!==undefined&&item!==null);
    if(typeof value==="object"){const result={};for(const [childKey,child] of Object.entries(value)){if(["blob","file","dataUrl","base64","objectUrl","photo","signatureData","signatureImage"].includes(childKey))continue;const next=compact(child,childKey);if(next!==undefined)result[childKey]=next;}return result;}
    return undefined;
  }
  function lightRecord(payload,draftKey,status){const clean=compact(payload),evidence=(clean.evidence||[]).map(evidenceReference);return{storageVersion:50,id:clean.id,draftKey,indexedDbRef:clean.id,workId:clean.workId||localStorage.getItem("gvc-active-work-id")||"legacy",type:clean.type||"incident",folio:clean.folio||clean.documentNumber||"",date:clean.date||"",status:status||clean.status||"Borrador",location:clean.location||"",description:String(clean.description||"").slice(0,800),evidence,evidenceCount:evidence.length,syncStatus:status||clean.syncStatus||"draft",updatedAt:clean.updatedAt||now()};}
  function safeLocalSet(key,value){const text=typeof value==="string"?value:JSON.stringify(value);if(serializedBytes(text)>LIGHT_LIMIT_BYTES)return{ok:false,reason:"limit",bytes:serializedBytes(text)};try{localStorage.setItem(key,text);return{ok:true,bytes:serializedBytes(text)};}catch(error){console.error(`[GraviIncidentStorage:set:${key}]`,error);return{ok:false,reason:isQuotaError(error)?"quota":"storage",error,bytes:serializedBytes(text)};}}
  function dataUrlToBlob(source){const [header,body]=source.split(",",2),mime=/^data:([^;,]+)/i.exec(header)?.[1]||"application/octet-stream",binary=atob(body),bytes=new Uint8Array(binary.length);for(let index=0;index<binary.length;index++)bytes[index]=binary.charCodeAt(index);return new Blob([bytes],{type:mime});}
  async function persistEvidence(payload){const queue=global.GraviOfflineEvidenceQueue;if(!queue)return compact(payload);const workId=payload.workId||localStorage.getItem("gvc-active-work-id")||"legacy",sourceModule=payload.type==="incident"?"incident":payload.type||"inspection",references=[];for(const source of payload.evidence||[]){const item=typeof source==="string"?{src:source}:source||{},encoded=[item.src,item.dataUrl,item.photo].find(dataUrl),blob=item.blob||encoded&&dataUrlToBlob(encoded),clientUuid=item.clientUuid||item.id||uuid();if(blob){await queue.save({clientUuid,blob,mimeType:item.mimeType||blob.type,originalName:item.originalName||`evidencia-${clientUuid}.jpg`,originalSize:item.originalSize||blob.size,sizeBytes:item.sizeBytes||blob.size,caption:item.caption||item.comment||"",recordType:"work_evidence",recordId:payload.id,workId,evidenceStage:sourceModule,sourceModule,sourceEntryId:payload.id,status:item.syncStatus==="synced"?"synced":"pending",storagePath:item.storagePath||""});}references.push(evidenceReference({...item,clientUuid,mimeType:item.mimeType||blob?.type,sizeBytes:item.sizeBytes||blob?.size}));}return{...compact(payload),evidence:references};}
  async function saveDraft(draftKey,payload,options={}){const id=payload.id||uuid(),workId=payload.workId||localStorage.getItem("gvc-active-work-id")||"legacy",clean=await persistEvidence({...payload,id,workId}),status=options.status||clean.syncStatus||"draft";await global.GraviOfflineEvidenceQueue.saveReport({id,draftKey,workId,status,payload:clean,clientMutationId:clean.clientMutationId||id});const light=lightRecord(clean,draftKey,status),local=safeLocalSet(draftKey,light);return{id,clean,light,local,quotaFallback:local.reason==="quota"||local.reason==="limit"};}
  async function saveArtifact(draftKey,payload,options={}){const id=payload.id||uuid(),workId=payload.workId||localStorage.getItem("gvc-active-work-id")||"legacy",clean=await persistEvidence({...payload,id,workId}),status=options.status||"draft";await global.GraviOfflineEvidenceQueue.saveReport({id,draftKey,workId,status,payload:clean,clientMutationId:id});let local=safeLocalSet(draftKey,clean);if(!local.ok)local=safeLocalSet(draftKey,lightRecord(clean,draftKey,status));return{id,clean,local,quotaFallback:!local.ok};}
  async function hydrate(payload){if(!payload)return payload;const evidence=[];for(const reference of payload.evidence||[]){const stored=await global.GraviOfflineEvidenceQueue?.get?.(reference.clientUuid||reference.id);evidence.push(stored?.blob?{...reference,...stored,src:URL.createObjectURL(stored.blob),objectUrl:""}:{...reference,src:reference.storageUrl||""});}return{...payload,evidence};}
  async function loadDraft(draftKey){let pointer=null;try{pointer=JSON.parse(localStorage.getItem(draftKey)||"null");}catch(error){console.error(`[GraviIncidentStorage:read:${draftKey}]`,error);}if(pointer?.indexedDbRef){const stored=await global.GraviOfflineEvidenceQueue?.getReport?.(pointer.indexedDbRef);return hydrate(stored?.payload||pointer);}const matches=await global.GraviOfflineEvidenceQueue?.listReports?.({draftKey});return hydrate(matches?.sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)))[0]?.payload||pointer);}
  async function saveRecord(payload){const clean=compact(payload),records=(()=>{try{return JSON.parse(localStorage.getItem(RECORDS_KEY)||"[]");}catch{return[];}})().filter(item=>item.id!==clean.id);records.unshift(clean);return{record:clean,local:safeLocalSet(RECORDS_KEY,records)};}
  async function removeDraft(draftKey,id){try{localStorage.removeItem(draftKey);}catch(error){console.error(`[GraviIncidentStorage:remove:${draftKey}]`,error);}if(id)await global.GraviOfflineEvidenceQueue?.deleteReport?.(id);}
  async function migratePayload(key,payload){const id=payload.id||uuid(),saved=await saveDraft(key,{...payload,id},{status:payload.syncStatus||"draft"});return saved.light;}
  async function migrateLegacy(){if(localStorage.getItem(MIGRATION_KEY)==="done")return{skipped:true};let migrated=0,failed=0;const keys=[];for(let index=0;index<localStorage.length;index++){const key=localStorage.key(index);if(key?.startsWith(DRAFT_PREFIX))keys.push(key);}for(const key of keys){try{const payload=JSON.parse(localStorage.getItem(key)||"null");if(payload&&!payload.indexedDbRef){await migratePayload(key,payload);migrated++;}}catch(error){failed++;console.error(`[GraviIncidentStorage:migrate:${key}]`,error);}}try{const records=JSON.parse(localStorage.getItem(RECORDS_KEY)||"[]");if(Array.isArray(records)){const migratedRecords=[];for(const record of records){if(record?.type==="incident"&&(record.evidence||[]).some(item=>dataUrl(typeof item==="string"?item:item?.src||item?.dataUrl||item?.photo))){const clean=await persistEvidence(record);await global.GraviOfflineEvidenceQueue.saveReport({id:clean.id,draftKey:"",workId:clean.workId||"legacy",status:clean.syncStatus||"synced",payload:clean,clientMutationId:clean.id});migratedRecords.push(clean);migrated++;}else migratedRecords.push(compact(record));}safeLocalSet(RECORDS_KEY,migratedRecords);}}catch(error){failed++;console.error("[GraviIncidentStorage:migrate:records]",error);}safeLocalSet(MIGRATION_KEY,"done");return{migrated,failed};}
  async function migrateSystemMedia(){const key="gvc-ops-system-v1";let system;try{system=JSON.parse(localStorage.getItem(key)||"null");}catch(error){console.error("[GraviIncidentStorage:migrate:system]",error);return 0;}if(!system)return 0;let migrated=0;for(const worker of system.workers||[]){if(!dataUrl(worker.photo))continue;const clientUuid=`worker-photo-${worker.id||uuid()}`,blob=dataUrlToBlob(worker.photo);await global.GraviOfflineEvidenceQueue.save({clientUuid,blob,mimeType:blob.type,originalName:`trabajador-${worker.id||clientUuid}.jpg`,originalSize:blob.size,sizeBytes:blob.size,caption:"Fotografía de trabajador",recordType:"work_evidence",recordId:worker.id||clientUuid,workId:worker.workId||"legacy",evidenceStage:"worker-photo",sourceModule:"worker-photo",sourceEntryId:worker.id||clientUuid,status:"pending"});worker.photo=`idb-evidence:${clientUuid}`;migrated++;}if(migrated)try{localStorage.setItem(key,JSON.stringify(system));}catch(error){console.error("[GraviIncidentStorage:migrate:system-write]",error);}return migrated;}
  const migrateLegacyBase=migrateLegacy;
  migrateLegacy=async function(){if(await global.GraviOfflineEvidenceQueue?.getReport?.("__migration-v50"))return{skipped:true};await migrateSystemMedia();const result=await migrateLegacyBase();await global.GraviOfflineEvidenceQueue?.saveReport?.({id:"__migration-v50",draftKey:"",workId:"",status:"migrated",payload:{completedAt:now()},clientMutationId:"__migration-v50"});return result;};
  let syncPromise=null;
  function syncPending(){if(syncPromise)return syncPromise;syncPromise=(async()=>{if(!navigator.onLine||!global.GraviSupabase?.isAuthenticated?.())return{synced:0,pending:true};const reports=await global.GraviOfflineEvidenceQueue?.listReports?.({statuses:["pending","sending","error"]})||[];let synced=0;for(const report of reports){try{const result=await global.GraviSupabase.entityMutations?.createIncident?.({...report.payload,clientMutationId:report.clientMutationId||report.id});if(result&&!result.pending){await global.GraviEvidenceManager?.uploadPending?.();await removeDraft(report.draftKey,report.id);synced++;}}catch(error){console.error(`[GraviIncidentStorage:sync:${report.id}]`,error);await global.GraviOfflineEvidenceQueue.saveReport({...report,status:"error",lastError:error?.message||"Error de sincronización"});}}return{synced,pending:false};})().finally(()=>{syncPromise=null;});return syncPromise;}
  global.addEventListener("online",()=>setTimeout(()=>void syncPending(),0));
  global.addEventListener("gvc:auth-ready",()=>setTimeout(()=>void syncPending(),0));
  global.GraviIncidentStorage=Object.freeze({saveDraft,saveArtifact,loadDraft,saveRecord,removeDraft,migrateLegacy,syncPending,persistEvidence,compact,lightRecord,safeLocalSet,serializedBytes,isQuotaError,constants:Object.freeze({DRAFT_PREFIX,RECORDS_KEY,MIGRATION_KEY,LIGHT_LIMIT_BYTES})});
})(window);
