(function signatureSystem(global){
"use strict";
const DB="gvc-document-signatures-v1",STORE="pending_signatures";
const DOCUMENT_SIGNATURE_CONFIG=Object.freeze({
  work_permit:{slots:[
    {key:"contractor_responsible",label:"Responsable del contratista",signerType:"external_person",requiredFor:["active"],acceptanceText:"Declaro haber revisado los riesgos, medidas preventivas, equipo de protección personal y condiciones establecidas en este permiso.",requiresName:true,requiresPosition:true,requiresCompany:true,order:1,invalidatedByRelevantChange:true},
    {key:"sst_supervisor",label:"Supervisor SST",signerType:"authenticated_user",requiredFor:["authorized","active"],acceptanceText:"Confirmo que revisé las condiciones del área y que las medidas preventivas requeridas se encuentran implementadas.",requiresName:true,requiresPosition:true,requiresCompany:false,order:2,invalidatedByRelevantChange:true},
    {key:"closure_contractor",label:"Responsable del contratista — cierre",signerType:"external_person",requiredFor:["closed"],acceptanceText:"Confirmo la conclusión de los trabajos y la entrega del área en las condiciones registradas.",requiresName:true,requiresPosition:true,requiresCompany:true,order:3,invalidatedByRelevantChange:false},
    {key:"closure_sst",label:"Supervisor SST — liberación",signerType:"authenticated_user",requiredFor:["closed"],acceptanceText:"Confirmo la revisión final y liberación del área.",requiresName:true,requiresPosition:true,requiresCompany:false,order:4,invalidatedByRelevantChange:false}
  ]},
  ats:{slots:[]},work_suspension:{slots:[]},ppe_delivery:{slots:[]},inspection:{slots:[]},dynamic_format:{slots:[]}
});
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function openDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB,1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:"clientUuid"})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function putPending(item){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(item);tx.oncomplete=()=>resolve(item);tx.onerror=()=>reject(tx.error)})}
async function listPending(){const db=await openDb();return new Promise((resolve,reject)=>{const req=db.transaction(STORE).objectStore(STORE).getAll();req.onsuccess=()=>resolve(req.result||[]);req.onerror=()=>reject(req.error)})}
async function removePending(id){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function syncPending(){if(!navigator.onLine||!global.GraviSupabase?.isAuthenticated?.()||!global.GraviSupabase?.signatures||global.GraviSupabase.canPermission?.("signatures.capture")!==true)return{synced:0};let synced=0;for(const item of await listPending()){try{item.attempts=Number(item.attempts||0)+1;item.lastAttemptAt=new Date().toISOString();await putPending(item);const remote=await global.GraviSupabase.signatures.upload(item);await removePending(item.clientUuid);global.dispatchEvent(new CustomEvent("gvc:signature-synced",{detail:{clientUuid:item.clientUuid,remote}}));synced++}catch(error){item.lastError=error.message;item.signatureStatus="pending_sync";await putPending(item);global.dispatchEvent(new CustomEvent("gvc:signature-sync-error",{detail:{clientUuid:item.clientUuid,error:error.message}}))}}return{synced}}
function contentHash(value){const stable=JSON.stringify(value,Object.keys(value||{}).sort());let hash=2166136261;for(let i=0;i<stable.length;i++){hash^=stable.charCodeAt(i);hash=Math.imul(hash,16777619)}return`fnv1a-${(hash>>>0).toString(16)}`}
function relevantPermitContent(p={}){return{activity:p.activity,description:p.description,executionArea:p.executionArea,contractorName:p.contractorName,contractorResponsible:p.contractorResponsible,hazards:p.hazards,ppe:p.ppe,preventive:p.preventive,controls:p.controls,participants:p.participants,startsAt:p.startsAt,endsAt:p.endsAt,workTypes:p.workTypes,authorization:p.authorizationAssessment}}
function createCapture(options={}){if(global.GraviSupabase?.canPermission?.("signatures.capture")!==true)throw new Error("Tu perfil no permite capturar firmas.");const slot=options.slot||{},modal=document.createElement("div");modal.className="signature-modal";modal.dataset.permission="signatures.capture";modal.innerHTML=`<section role="dialog" aria-modal="true" aria-label="Firma manuscrita capturada en dispositivo"><header><div><h2>Firma manuscrita capturada en dispositivo</h2><p>${esc(slot.label||options.roleLabel||"")}</p></div><button type="button" data-sign-cancel aria-label="Cerrar">×</button></header><div class="signature-fields"><label>Nombre del firmante<input data-sign-name value="${esc(options.signerName||"")}"></label><label>Cargo<input data-sign-position value="${esc(options.signerPosition||"")}"></label><label>Empresa<input data-sign-company value="${esc(options.signerCompany||"")}"></label></div><p class="signature-declaration">${esc(slot.acceptanceText||options.acceptanceText||"")}</p><canvas aria-label="Área para firma manuscrita"></canvas><p class="signature-help">Firme con el dedo, lápiz, mouse o tableta digitalizadora.</p><label class="signature-consent"><input type="checkbox" data-sign-consent> Confirmo la declaración anterior y acepto asociar esta firma exclusivamente a este documento y versión.</label><p data-sign-message role="alert"></p><footer><button type="button" data-sign-undo>Deshacer</button><button type="button" data-sign-clear>Borrar</button><span></span><button type="button" data-sign-cancel>Cancelar</button><button type="button" data-sign-accept data-permission="signatures.capture">Aceptar firma</button></footer></section>`;
  const canvas=modal.querySelector("canvas"),ctx=canvas.getContext("2d"),strokes=[];let activeStroke=null,locked=Boolean(options.locked);if(options.previewUrl){const img=document.createElement("img");img.className="signature-existing-preview";img.src=options.previewUrl;img.alt=`Firma manuscrita de ${options.signerName||"firmante"}`;canvas.insertAdjacentElement("beforebegin",img);if(locked){canvas.hidden=true;modal.querySelector("[data-sign-accept]").hidden=true;modal.querySelector("[data-sign-clear]").hidden=true;modal.querySelector("[data-sign-undo]").hidden=true}}
  function resize(){const rect=canvas.getBoundingClientRect(),ratio=Math.max(1,global.devicePixelRatio||1),old=[...strokes];canvas.width=Math.max(1,Math.round(rect.width*ratio));canvas.height=Math.max(1,Math.round(rect.height*ratio));ctx.setTransform(ratio,0,0,ratio,0,0);draw(old)}
  function draw(list=strokes){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.lineWidth=2.2;ctx.lineCap="round";ctx.lineJoin="round";ctx.strokeStyle="#10213a";list.forEach(points=>{if(points.length<2)return;ctx.beginPath();ctx.moveTo(points[0].x*canvas.clientWidth,points[0].y*canvas.clientHeight);points.slice(1).forEach(p=>ctx.lineTo(p.x*canvas.clientWidth,p.y*canvas.clientHeight));ctx.stroke()})}
  const point=e=>{const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height,t:Date.now(),pressure:e.pressure||.5,pointerType:e.pointerType}};
  canvas.onpointerdown=e=>{if(locked)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);activeStroke=[point(e)];strokes.push(activeStroke)};
  canvas.onpointermove=e=>{if(!activeStroke||locked)return;e.preventDefault();activeStroke.push(point(e));draw()};
  const end=e=>{if(!activeStroke)return;e.preventDefault();activeStroke.push(point(e));activeStroke=null;draw()};canvas.onpointerup=end;canvas.onpointercancel=end;
  const message=text=>modal.querySelector("[data-sign-message]").textContent=text;
  modal.querySelector("[data-sign-undo]").onclick=()=>{if(!locked){strokes.pop();draw()}};modal.querySelector("[data-sign-clear]").onclick=()=>{if(!locked){strokes.length=0;draw()}};
  modal.querySelectorAll("[data-sign-cancel]").forEach(b=>b.onclick=()=>{modal.remove();options.onCancel?.()});
  modal.querySelector("[data-sign-accept]").onclick=async()=>{const name=modal.querySelector("[data-sign-name]").value.trim(),position=modal.querySelector("[data-sign-position]").value.trim(),company=modal.querySelector("[data-sign-company]").value.trim(),consent=modal.querySelector("[data-sign-consent]").checked,points=strokes.reduce((n,s)=>n+s.length,0),bounds=strokes.flat().reduce((b,p)=>({minX:Math.min(b.minX,p.x),maxX:Math.max(b.maxX,p.x),minY:Math.min(b.minY,p.y),maxY:Math.max(b.maxY,p.y)}),{minX:1,maxX:0,minY:1,maxY:0});if(!name)return message("Capture el nombre del firmante.");if(!position)return message("Capture el cargo o rol del firmante.");if(slot.requiresCompany&& !company)return message("Capture la empresa del firmante.");if(!consent)return message("Debe confirmar la declaración de aceptación.");if(strokes.length<1||points<6||(bounds.maxX-bounds.minX<.04&&bounds.maxY-bounds.minY<.04))return message("La firma está vacía o es demasiado pequeña.");const blob=await new Promise((resolve,reject)=>canvas.toBlob(x=>x?resolve(x):reject(new Error("No fue posible generar la firma.")),"image/png"));const result={clientUuid:crypto.randomUUID(),documentType:options.documentType,documentId:options.documentId,documentVersion:String(options.documentVersion||"1"),signatureSlot:slot.key||options.signatureSlot,signerType:slot.signerType||options.signerType||"other",signerUserId:options.signerUserId||null,signerName:name,signerPosition:position,signerCompany:company,signerRoleLabel:slot.label||options.roleLabel,acceptanceText:slot.acceptanceText||options.acceptanceText,acceptanceConfirmed:true,signedAt:new Date().toISOString(),capturedByUserId:options.capturedByUserId||null,capturedInPresenceOfUserId:options.capturedInPresenceOfUserId||null,documentContentHash:options.documentContentHash,documentStatusAtSigning:options.documentStatus,signatureStatus:"pending_sync",strokesData:strokes,width:canvas.width,height:canvas.height,strokeCount:strokes.length,blob,attempts:0,lastError:null};await putPending(result);modal.remove();options.onAccept?.(result)};
  document.body.appendChild(modal);requestAnimationFrame(resize);global.addEventListener("resize",resize,{once:true});document.body.classList.add("signature-capture-open");new MutationObserver(()=>{if(!modal.isConnected)document.body.classList.remove("signature-capture-open")}).observe(document.body,{childList:true});return{modal,canvas,strokes,resize,clear:()=>{strokes.length=0;draw()}};
}
global.addEventListener("online",syncPending);global.addEventListener("gvc:auth-ready",syncPending);
global.GraviSignatures=Object.freeze({config:DOCUMENT_SIGNATURE_CONFIG,createCapture,contentHash,relevantPermitContent,syncPending,offline:{put:putPending,list:listPending,remove:removePending}});
})(window);
